### ISSUE TITLE
installation problem on RHES

### ISSUE THREAD

**Issue by dclambert** [minepy/minepy#14]
```
unix> lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.9 (Santiago)
Release:        6.9
Codename:       Santiago
```

```
unix> pip install minepy
Collecting minepy
  Using cached minepy-1.2.2.tar.gz
Requirement already satisfied: numpy>=1.3.0 in /home/foo/miniconda3/envs/CE/lib/python3.5/site-packages (from minepy)
Building wheels for collected packages: minepy
  Running setup.py bdist_wheel for minepy ... error
  Failed building wheel for minepy
  Running setup.py clean for minepy
Failed to build minepy
Installing collected packages: minepy
  Running setup.py install for minepy ... error
Exception:
Traceback (most recent call last):
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 83: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/home/foo/miniconda3/envs/CE/lib/python3.5/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 83: invalid start byte
```

**Comment by davidealbanese** [comment]
Probably the problem is related to pip or miniconda3/pip, see pypa/pip#4110.
